# Generated by Django 4.0 on 2022-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_items', models.PositiveSmallIntegerField(default=0)),
                ('current_item', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(max_length=300)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Finish'), (2, 'Processing'), (3, 'Error')], null=True)),
            ],
        ),
    ]
