# Generated by Django 4.0 on 2022-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='anna_for_teens',
        ),
        migrations.AddField(
            model_name='car',
            name='one_two_adults_back_seat',
            field=models.BooleanField(default=False, verbose_name='1 & 2 Adults back seat'),
        ),
    ]
