# Generated by Django 4.0 on 2022-09-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_anna_for_teens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='one_two_adults_back_seat',
        ),
    ]
