# Generated by Django 4.0 on 2022-09-10 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_one_two_adults_back_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='extreme_off_road',
            new_name='heavy_off_road',
        ),
        migrations.AlterField(
            model_name='car',
            name='race_track',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'No'), (2, 'Medium'), (3, 'Yes')], help_text='range (1-10)', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
