# Generated by Django 4.0 on 2022-09-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_extreme_off_road_car_heavy_off_road_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='uber_recommendation',
        ),
    ]
