# Generated by Django 4.0 on 2022-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_uber_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_au',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_nz',
            field=models.FloatField(null=True),
        ),
    ]
