# Generated by Django 4.0 on 2022-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_price_au_car_price_nz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_au',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_nz',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
