# Generated by Django 4.0 on 2022-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_price_au_alter_car_price_nz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='warranty_years',
        ),
        migrations.AddField(
            model_name='car',
            name='warranty_years_au',
            field=models.PositiveIntegerField(null=True, verbose_name='Warranty AU (Years)'),
        ),
        migrations.AddField(
            model_name='car',
            name='warranty_years_nz',
            field=models.PositiveIntegerField(null=True, verbose_name='Warranty NZ (Years)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ancap',
            field=models.PositiveIntegerField(null=True, verbose_name='ANCAP'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_au',
            field=models.PositiveIntegerField(null=True, verbose_name='Price AU'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_nz',
            field=models.PositiveIntegerField(null=True, verbose_name='Price NZ'),
        ),
    ]
