# Generated by Django 4.0 on 2022-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_warranty_years_car_warranty_years_au_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='warranty_distance',
            field=models.CharField(max_length=100, null=True, verbose_name='Warranty AU (KM)'),
        ),
    ]
