# Generated by Django 4.0 on 2022-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_warranty_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(null=True, verbose_name='Acceleration 0-100'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ancap',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ANCAP'),
        ),
        migrations.AlterField(
            model_name='car',
            name='battery_warranty_distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery warranty (KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='battery_warranty_years',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery warranty (Years)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.PositiveIntegerField(max_length=100, null=True, verbose_name='Power (HP)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_kw',
            field=models.PositiveIntegerField(max_length=100, null=True, verbose_name='Power (kW)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Top speed (KM/H)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='torque_nm',
            field=models.PositiveIntegerField(null=True, verbose_name='Power (Nm)'),
        ),
    ]
