# Generated by Django 4.0 on 2022-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_charging_time_alter_car_electric_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.PositiveIntegerField(null=True, verbose_name='Power (HP)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_kw',
            field=models.PositiveIntegerField(null=True, verbose_name='Power (kW)'),
        ),
    ]
