# Generated by Django 4.0 on 2022-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_power_hp_alter_car_power_kw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'All Wheel Drive'), (2, 'Front Wheel Drive'), (3, 'Rear Wheel Drive')], null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='race_track',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'No'), (2, 'Medium'), (3, 'Well')], null=True),
        ),
    ]
