# Generated by Django 4.0 on 2022-09-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_drive_alter_car_race_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbody',
            options={'ordering': ('name',), 'verbose_name_plural': 'Car bodies'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('brand__name',)},
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carbody'),
        ),
    ]
