# Generated by Django 4.0 on 2022-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_carbody_options_alter_carbrand_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_for_man',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_for_woman',
        ),
        migrations.AlterField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(blank=True, null=True, verbose_name='Acceleration 0-100'),
        ),
        migrations.AlterField(
            model_name='car',
            name='charging_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Charging time 0-100% 7.4 KW'),
        ),
        migrations.AlterField(
            model_name='car',
            name='electric_range',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Electric range (KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_average_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel average distance (KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel capacity L'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_combined',
            field=models.FloatField(blank=True, null=True, verbose_name='Fuel combined (L/KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_urban',
            field=models.FloatField(blank=True, null=True, verbose_name='Fuel urban (L/KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='max_boot_space',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max boot space (L)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='max_fuel_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max fuel distance (KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='min_boot_space',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Min boot space (L)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='min_fuel_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Min fuel distance (KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Power (HP)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_rpm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Power (rpm)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_au',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price AU'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_nz',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price NZ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Top speed (KM/H)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='torque_nm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Power (Nm)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='torque_rpm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='torque (rpm)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='warranty_distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Warranty AU (KM)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='warranty_years_au',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Warranty AU (Years)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='warranty_years_nz',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Warranty NZ (Years)'),
        ),
        migrations.AlterField(
            model_name='carbody',
            name='image',
            field=models.ImageField(blank=True, upload_to='body_images'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='model_images'),
        ),
    ]
