# Generated by Django 4.0 on 2023-01-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_car_max_charging_time_car_max_charging_time_max_kw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='max_charging_time_max_kw',
            new_name='max_charging_max_kw',
        ),
    ]
