# Generated by Django 4.0 on 2023-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_rename_max_charging_max_kw_car_fast_charging_max_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hot_hatch',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
