# Generated by Django 4.0 on 2023-04-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_car_hot_hatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
